name: Deploy PROD

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy-prod:
    name: Deploy PROD ${{ github.event.inputs.tag || github.ref }}
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ github.event.inputs.tag || github.ref }}

      - name: FTP Deploy
        uses: ./.github/actions/ftp-deploy
        with:
          server: ${{ secrets.DEPLOY_PROD_FTP_SERVER || 'ftp.oliro.es' }}
          username: ${{ secrets.DEPLOY_PROD_FTP_USER || 'public_html@oliro.es' }}
          password: ${{ secrets.DEPLOY_PROD_FTP_PASSWORD }}
          port: ${{ secrets.DEPLOY_PROD_FTP_PORT }}
          protocol: ${{ secrets.DEPLOY_PROD_FTP_PROTOCOL }}
          local-dir: react-build/
          server-dir: ./
          dangerous-clean-slate: true
